apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-k0e8
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-jukv-tenant/rhtap-demo-app/hacbs-test-project-k0e8@sha256:0cf7e861053603a493639134d94cbd280e61de4d5368c41a61ca891548b2cc04
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
