apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-k0e8
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-jukv-tenant/rhtap-demo-app/hacbs-test-project-k0e8@sha256:00852c7e97cb272a8654c8cc5eb65e2ef6479647d484e40f339fb49acc369e83
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
